version: '3'
services:
  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      TZ: "Europe/Stockholm"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - message-board

  migrate:
    image: migrate/migrate
    volumes:
      - "./backend/migrations/:/migrations"
    command: |
      -path=/migrations/
      -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?sslmode=disable
      up
    networks:
      - message-board
    depends_on:
      database:
        condition: service_healthy

  message-board:
    image: message-board:latest
    build:
      context: .
    networks:
      - message-board
    environment:
      DB_USER: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_NAME: "${POSTGRES_DB}"
      DB_HOST: database
      DB_PORT: 5432
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      migrate:
        condition: service_completed_successfully

networks:
  message-board:
    name: message-board
    driver: bridge
