CREATE TABLE IF NOT EXISTS author (
	id SERIAL PRIMARY KEY,
	username TEXT NOT NULL UNIQUE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS message (
	id BIGSERIAL PRIMARY KEY,
	parent_id INTEGER REFERENCES "message" (id),
	author_id INTEGER REFERENCES "author" (id),
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
